name: Publish E2E
on:
  workflow_run:
    workflows: ["Publish Node"]
    branches: [main]
    types: [completed]
env:
  BUILD_CONTAINER_IMAGE: xmtp/xmtpd-e2e:latest
jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build
        run: dev/docker/xmtpd-e2e/build
      - name: Push
        id: push
        run: |
          dev/docker/xmtpd-e2e/push
          echo "docker_image=$(docker inspect --format='{{index .RepoDigests 0}}' ${BUILD_CONTAINER_IMAGE})" >> $GITHUB_OUTPUT
      - name: Deploy (testnet-pizza)
        uses: xmtp-labs/terraform-deployer@v1
        with:
          terraform-token: ${{ secrets.TERRAFORM_TOKEN }}
          terraform-org: xmtp
          terraform-workspace: testnet-pizza
          variable-name: e2e_container_image
          variable-value: ${{ steps.push.outputs.docker_image }}
          variable-value-required-prefix: "xmtp/xmtpd-e2e@sha256:"
